package com.cn.mobileapp.family.entity;

import java.util.Date;

import com.cn.framework.mvc.mysql.entity.BaseSQLEntity;

/**
* @Project ChuFangLiuZhuan_PlatForm_Platorm
* @Package com.cn.platform.security.entity
* @ClassName com.cn.platform.security.entity.Family
* @TableName BIZ_FAMILY
* @Description
* @JDK version used 1.8.0_111-b14
* @Author Administrator
* @Create Date 2017年9月7日
* @modify By 
* @modify Date 
* @Why&What is modify 
* @Version 1.0
*/
public class Family extends BaseSQLEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BIZ_FAMILY
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = -525963286;

    /**
     * 姓名
     */
    private String fullname;

    /**
     * 电话
     */
    private String mobile;

    /**
     * 性别:1男，0女
     */
    private Integer sex;

    /**
     * 与用户关系：1-父亲2-母亲3-儿子4-女儿 5--其他
     */
    private Integer relation;

    /**
     * 证件号码
     */
    private String idCard;

    /**
     * 证件类别:1：二代身份证， 2：港澳通行证，3：护照
     */
    private Integer idType;

    /**
     * 出生年月
     */
    private Date birthday;

    /**
     * 年龄
     */
    private Integer age;

    /**
     * 状态 1正常 2 删除
     */
    private Integer status;

    /**
     * 监护人姓名
     */
    private String guarderName;

    /**
     * 监护人电话号码
     */
    private String guarderMobile;

    /**
     * 监护人证件类型
     */
    private Integer guarderCardtype;

    /**
     * 监护人证件号
     */
    private String guarderCardno;

    /**
     * 默认就诊人 0否 1是
     */
    private Integer defaultpatient;

    /**
     * 地址
     */
    private String address;

    /**
    * @return 姓名
    */
    public String getFullname() {
        return fullname;
    }

    /**
     * @param fullname  姓名
     */
    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }

    /**
    * @return 电话
    */
    public String getMobile() {
        return mobile;
    }

    /**
     * @param mobile  电话
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }


    /**
    * @return 证件号码
    */
    public String getIdCard() {
        return idCard;
    }

    /**
     * @param idCard  证件号码
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }


    /**
    * @return 出生年月
    */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * @param birthday  出生年月
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
    * @return 监护人姓名
    */
    public String getGuarderName() {
        return guarderName;
    }

    /**
     * @param guarderName  监护人姓名
     */
    public void setGuarderName(String guarderName) {
        this.guarderName = guarderName == null ? null : guarderName.trim();
    }

    /**
    * @return 监护人电话号码
    */
    public String getGuarderMobile() {
        return guarderMobile;
    }

    /**
     * @param guarderMobile  监护人电话号码
     */
    public void setGuarderMobile(String guarderMobile) {
        this.guarderMobile = guarderMobile == null ? null : guarderMobile.trim();
    }

    /**
    * @return 监护人证件号
    */
    public String getGuarderCardno() {
        return guarderCardno;
    }

    /**
     * @param guarderCardno  监护人证件号
     */
    public void setGuarderCardno(String guarderCardno) {
        this.guarderCardno = guarderCardno == null ? null : guarderCardno.trim();
    }


    /**
    * @return 地址
    */
    public String getAddress() {
        return address;
    }

    /**
     * @param address  地址
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

	public Integer getSex() {
		return sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	public Integer getRelation() {
		return relation;
	}

	public void setRelation(Integer relation) {
		this.relation = relation;
	}

	public Integer getIdType() {
		return idType;
	}

	public void setIdType(Integer idType) {
		this.idType = idType;
	}

	public Integer getAge() {
		return age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getGuarderCardtype() {
		return guarderCardtype;
	}

	public void setGuarderCardtype(Integer guarderCardtype) {
		this.guarderCardtype = guarderCardtype;
	}

	public Integer getDefaultpatient() {
		return defaultpatient;
	}

	public void setDefaultpatient(Integer defaultpatient) {
		this.defaultpatient = defaultpatient;
	}
    
}