/**
* <html>
*
*   <P> Copyright 2017 阳光康众 </p>
*
*   <p> Created on 2017年9月6日</p>
*   <p> Created by Administrator</p>
*  </body>
* </html>
*/
package com.cn.mobileapp.login.entity;

import com.cn.framework.mvc.mysql.entity.BaseSQLEntity;

/**
* @Project ChuFangLiuZhuan_PlatForm_Platorm
* @Package com.cn.platform.security.entity
* @ClassName com.cn.platform.security.entity.AppUser
* @TableName BIZ_USER
* @Description
* @JDK version used 1.8.0_111-b14
* @Author Administrator
* @Create Date 2017年9月6日
* @modify By 
* @modify Date 
* @Why&What is modify 
* @Version 1.0
*/
public class AppUser extends BaseSQLEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BIZ_USER
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = -2028206545;

    /**
     * 用户账号
     */
    private String userAccount;

    /**
     * 用户密码
     */
    private String userPassword;

    /**
     * 用户姓名
     */
    private String userName;

    /**
     * 患者IDS
     */
    private String userPatient;

    /**
    * @return 用户账号
    */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * @param userAccount  用户账号
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
    * @return 用户密码
    */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * @param userPassword  用户密码
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
    * @return 用户姓名
    */
    public String getUserName() {
        return userName;
    }

    /**
     * @param userName  用户姓名
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
    * @return 患者IDS
    */
    public String getUserPatient() {
        return userPatient;
    }

    /**
     * @param userPatient  患者IDS
     */
    public void setUserPatient(String userPatient) {
        this.userPatient = userPatient == null ? null : userPatient.trim();
    }
}